### PR TITLE
Verify Strcture and Assembly Process

### PR DESCRIPTION
**Pull request by GregWallace24**
Fixes Issue #312 

Due end of Sunday Sept. 19
Add other teamleads to the assignees as needed

On the GrabCad go to:
CougSat1(Mk2, Master) -> Mk2V12 -> StructureAssemblyVOLUMEMODEL.SLDASM
Or on Github, see Issue  #314

Also look at the file in #312 

First, view the GrabCad file described above. You don’t need solidworks to view the design or take simple measurements, but it is recommended. You can get Solidworks for yourself from the school or you can access it in Sloan 249 (Message Colin or I and we will tell you how to get on the computers. I won’t write it here because this is publicly visible).

Then view the rough outline of the assembly process we intend to use (uploaded here). Several parts aren’t fully designed yet, so they aren’t in the model.

Your job for this issue is to verify that this structure design (Mk2V12) and assembly process do not interfere with your designs yet. This does not need to be the final design. The purpose is to push us all towards finalization.

If you cannot describe specifically how it interferes with your subsystem and don’t have detailed modification requests, then it does not interfere with your current design, so mark as accepted. You can always request edits later. This issue is NOT intended to verify everything fits: we can’t predict the future. For non-vital suggestions, we can set them up and implement them when we move onto the next revision (if we do another revision).

If this issue is accepted, then this is the structure will become Revision A, and will be the official one. After, we will assume there are no problems with the structure unless you notify us. For modification, you will need to create an issue. In the case of change, we will create a new revision and then again ask you all to verify that it does not interfere.

If it is not accepted then we will make the requested edits and ask you to verify again in a similar matter.

### CODE REVIEW

**Comment by WattsUp** [comment]
Please put the CAD files on GitHub.
The document you added goes into Documentation folder

**Comment by WattsUp** [comment]
There also needs a formal design review, set up a time when you can fly around the model and we ask questions. Unless you are able to write a design document explaining every design choice

**Comment by GregWallace24** [comment]
CAD is on github, see issue 314
Design review scheduling started in teamleads chat
Can't figure out how to move the document to a different folder.  @WattsUp How do I move it?

**Comment by WattsUp** [comment]
When committing, commit to the branch that has the pull request open, see #314

**Comment by GregWallace24** [comment]
That's what I'm trying to do.

**Pull request closed without merging**
