### PR TITLE
System requirements

### LINKED ISSUE #117: COUGSAT-1: Create System Requirements

### PR DESCRIPTION
**Pull request by WattsUp**
Fixes #117

### CODE REVIEW

**Comment by mvguerrero** [comment]
I approve of the ECS Design requirements so far. The only thing I don't know if we should add, would be a requirement to electrically ground or connect any insulation components which could develop charge differentials with other components.

**Comment by mvguerrero** [comment]
Here's what I would like to add to the document on the ECS page:

ECS-004 | The ECS should not carry a   dangerous difference of electric potential | Differences in electric   potential could cause arcs | REQ-009

Here's the document with the change I would like
[CougSat1-Requirements (1).xlsx](https://github.com/CougsInSpace/CougSat1-Hardware/files/2365191/CougSat1-Requirements.1.xlsx)

I think my requirement is sufficiently different than ECS-003 because 003 is only concerned with levels of ionization, rather than charge differentials developed from the exposure.

**Comment by WattsUp** [comment]
All components on the satellite should (and are) grounded together. Example: each board has its gold fingers that slide into the rails which are connected to ground, also every bolt mount is connected there, etc. This leads me to not put it in each subsystem design requirements but it I don't think it is high enough to become a system requirement. I recommend it is just clearly formalized in SOP. Is that okay @mvguerrero ?

**Comment by ugradbhull** [comment]
Req: PAYLOAD-004 
Change: Cameras need light to image and confirm seed germination
Reason: Seed do not need light to go through the first phase of germination, therefore it is not necessary to have lights to promote growth.

**Pull request merged**
